services:
  - type: web
    name: gdta-backend-django
    runtime: python
    repo: https://github.com/SRAMBOT08/GDTA2026
    region: oregon
    plan: free
    branch: django
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --threads 4 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://gdta-backend-django.onrender.com
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM_NAME
        value: GDTA 2026 Team
